openapi: 3.2.0
info:
  version: 0.0.1
  title: Alertmanager Receiver API
  description: API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: /api/v2/
tags:
- name: Receiver
  description: Everything related to Alertmanager receivers
paths:
  /receivers:
    get:
      tags:
      - Receiver
      operationId: getReceivers
      description: Get list of all receivers (name of notification integrations)
      parameters:
      - $ref: '#/components/parameters/receiverMatchers'
      responses:
        '200':
          description: Get receivers response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/receiver'
        '400':
          $ref: '#/components/responses/BadRequest'
      summary: Get receivers
      x-summary-source: derived
components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: string
  schemas:
    receiver:
      type: object
      properties:
        name:
          type: string
        labels:
          $ref: '#/components/schemas/labelSet'
      required:
      - name
    labelSet:
      type: object
      additionalProperties:
        type: string
  parameters:
    receiverMatchers:
      name: receiver_matchers
      in: query
      description: A matcher expression to filter by receiver labels. For example `owner="my-team"`. Can be repeated to apply multiple matchers.
      required: false
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
