openapi: 3.2.0
info:
  version: 0.0.1
  title: Alertmanager General API
  description: API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: /api/v2/
tags:
- name: General
  description: General Alertmanager operations
paths:
  /status:
    get:
      tags:
      - General
      operationId: getStatus
      description: Get current status of an Alertmanager instance and its cluster
      responses:
        '200':
          description: Get status response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/alertmanagerStatus'
      summary: Get status
      x-summary-source: derived
components:
  schemas:
    alertmanagerConfig:
      type: object
      properties:
        original:
          type: string
      required:
      - original
    clusterStatus:
      type: object
      properties:
        name:
          type: string
        status:
          type: string
          enum:
          - ready
          - settling
          - disabled
        peers:
          type: array
          items:
            $ref: '#/components/schemas/peerStatus'
      required:
      - status
    versionInfo:
      type: object
      properties:
        version:
          type: string
        revision:
          type: string
        branch:
          type: string
        buildUser:
          type: string
        buildDate:
          type: string
        goVersion:
          type: string
      required:
      - version
      - revision
      - branch
      - buildUser
      - buildDate
      - goVersion
    alertmanagerStatus:
      type: object
      properties:
        cluster:
          $ref: '#/components/schemas/clusterStatus'
        versionInfo:
          $ref: '#/components/schemas/versionInfo'
        config:
          $ref: '#/components/schemas/alertmanagerConfig'
        uptime:
          type: string
          format: date-time
      required:
      - cluster
      - versionInfo
      - config
      - uptime
    peerStatus:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
      required:
      - name
      - address
